# Generated by Django 3.0.7 on 2020-06-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_emailnews_newslettersubscriber_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='price',
        ),
    ]
