# Generated by Django 3.0.7 on 2020-06-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contackuscomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContackUsComment',
            new_name='ContactUsComment',
        ),
    ]
