# Generated by Django 3.0.7 on 2020-07-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200703_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuscomment',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributor',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
