# Generated by Django 3.0.7 on 2020-07-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200703_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Pending payment'), (2, 'Payment done'), (3, 'Packed'), (4, 'Shipped'), (5, 'Delivered'), ('6', 'Returned')], default=1, max_length=1),
        ),
    ]
