# Generated by Django 3.0.7 on 2020-07-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200703_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total',
        ),
        migrations.AddField(
            model_name='productlist',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
