# Generated by Django 3.0.7 on 2020-07-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200703_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Pending payment'), ('2', 'Payment done'), ('3', 'Packed'), ('4', 'Shipped'), ('5', 'Delivered'), ('6', 'Returned'), ('7', 'Canceld')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_name',
            field=models.TextField(),
        ),
    ]
