# Generated by Django 3.0.7 on 2020-07-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200704_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='order',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
