# Generated by Django 3.0.7 on 2020-07-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200704_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('1', 'Pending payment'), ('2', 'Payment done')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('3', 'Packed'), ('4', 'Shipped'), ('5', 'Delivered'), ('6', 'Returned'), ('7', 'Canceld')], default='?', max_length=1),
        ),
    ]
